# Custom Flake8 configuration for community add-on template
# Based on NVDA's Flake8 configuration with modifications for the basic add-on template (edited by Joseph Lee)

[flake8]

# Reporting
statistics = True
doctests = True
show-source = True

# Options
max-complexity = 15
max-line-length = 110
# Final bracket should match indentation of the start of the line of the opening bracket
hang-closing = False

ignore =
	W191,
	W503,

builtins = # inform flake8 about functions we consider built-in.
	_,
	ngettext,
	pgettext,
	npgettext,

exclude = # don't bother looking in the following subdirectories / files.
	.git,
	__pycache__,
	buildVars.py,
	site_scons/*
